### ISSUE TITLE
missing  libgcc_s_sjlj-1.dll

### ISSUE THREAD

**Issue by silentwings** [spring/SpringMapConvNG#1]
Using win-64 build from https://springrts.com/wiki/MapConvNG

At the moment (at least on Windows) when run it asks that libgcc_s_sjlj-1.dll be externally present, which it isn't in the current wiki dl. I tried manually placing a version of that dll next to the exe, which resulted in the new error "The application was unable to start correctly (0xc000007b)."

Probably it should be compiled with -static-libgcc

**Comment by abma** [comment]
is this error from 32 bit or the 64 bit version?

updated the 32 bit version: https://springrts.com/phpbb/viewtopic.php?f=13&t=26669&start=40#p585335

**Comment by silentwings** [comment]
The error above was from the 64 bit build offered on the wiki.

The 32 bit version from your link seems fixed.

**Comment by abma** [comment]
ok, removed the link to the broken file.
