### ISSUE TITLE
Statically compile the compiler for Linux (and Windows.. and Mac..)

### ISSUE THREAD

**Issue by gajop** [spring/SpringMapConvNG#2]
I am [in need](https://github.com/Spring-SpringBoard/SpringBoard-Core/issues/276) of a map compiler I can distribute to my users with SpringBoard, so let's choose this one - it seems good and worked without issues each time I used it.

The problem: it should be statically compiled or distributed with the required dlls (.so-s) or otherwise it's unusable: if users need to compile it themselves or install it with a package manager it defeats the purpose of using SpringBoard. Map compilation becomes too difficult and honestly it has no right to be.

My approach to this would normally be to convert this project to use package managers instead (which I think we should try for spring and pr-downloader as well - too many development and usage issues, e.g. the recent libcurl3/4 annoyance with Ubuntu 18.04 and other Linuxes).

However, it seems devil (the only library used here) has not been under active development for quite some time, and isn't hosted on the two package managers I checked: [Hunter](https://docs.hunter.sh) or [Conan](https://conan.io/)

The way I see it, there are a couple of solutions:
1. Figure out how to make it statically compile on Linux by altering the existing cmake files, without a package manager
2. Get someone to host it on one of those two package managers for us. In this way we can have a guarantee that a well tested version (which usually statically compiles) also exists.
3. Replace Devil with an actively developed lib, (maybe even a real C++ lib this time), either one that's hosted on a package manager or that is header only: I haven't tried them all, but it seems that our main requirement is that the library has DXTC support. Also, I am not just suggesting we change a working system. Devil has a number of issues for me, e.g. [confirmed](https://github.com/Spring-SpringBoard/SpringBoard-Core/issues/284) and [unconfirmed](https://github.com/Spring-SpringBoard/SpringBoard-Core/issues/329)

Btw, how am I supposed to distribute for Windows? We also need a buildbot, in any of these situations. I once went into the rabbit hellhole that is fixing static cmake compilation on mxe without accomplishing anything besides getting frustrated and wasting time. I'd avoid doing that again.

Looking for some feedback before I attempt a solution (most likely 3.)

**Comment by gajop** [comment]
Further examples why I don't want to be a build engineer: https://github.com/DentonW/DevIL/pull/59#issuecomment-352267464

What is a build engineer anyway? It's not like people take CMake as a major at a uni. Does one get to call theirself a build engineer after suffering enough with build tools?

**Comment by abma** [comment]
add SpringMapConvNG to the spring repo as submodule and let it ship with spring?

**Comment by gajop** [comment]
I wouldn't mind that solution for the time being, but I'd basically just copy the executable once it gets bult.
That helps us with the buildbot issue (which isn't the biggest issue, I already resigned to have to run my own Windows buildbot for other stuff), but how do we make it statically linked?

**Comment by abma** [comment]
https://github.com/spring/spring-lxc/blob/master/scripts/cfg/install/make_static_libs.sh

**Comment by gajop** [comment]
I think it would be better to build these projects separately. Make Spring leaner and easier to build (now and in the future).
Do you think we could build more things using those buildbots, but with some modularity?
I'm willing to help out if you can give me some instructions (looking at the buildbot pages for now)

**Comment by abma** [comment]
there was/is already a download link: https://springrts.com/wiki/MapConvNG

**Comment by gajop** [comment]
Need it to be static executable for Linux too :)

**Comment by gajop** [comment]
Any chance you could use your recently developed magic skills to also statically link this? (and provide a Linux/Win downloadable?)

**Comment by Oflameo** [comment]
I got springMapConvNG installed and printed a full list of the shared object decencies.

```
ldd springMapConvNG
        linux-vdso.so.1 (0x00007ffd94f75000)
        libIL.so.1 => /usr/lib/x86_64-linux-gnu/libIL.so.1 (0x00007ffb427e3000)
        libILU.so.1 => /usr/lib/x86_64-linux-gnu/libILU.so.1 (0x00007ffb425ce000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ffb4244a000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ffb42430000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffb4226f000)
        libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007ffb421f0000)
        libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007ffb421b5000)
        libmng.so.1 => /usr/lib/x86_64-linux-gnu/libmng.so.1 (0x00007ffb41f21000)
        liblcms2.so.2 => /usr/lib/x86_64-linux-gnu/liblcms2.so.2 (0x00007ffb41ec4000)
        libjpeg.so.62 => /usr/lib/x86_64-linux-gnu/libjpeg.so.62 (0x00007ffb41c5b000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ffb41a3d000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffb418ba000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ffb42d6b000)
        libwebp.so.6 => /usr/lib/x86_64-linux-gnu/libwebp.so.6 (0x00007ffb4164f000)
        libzstd.so.1 => /usr/lib/x86_64-linux-gnu/libzstd.so.1 (0x00007ffb415af000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007ffb41587000)
        libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007ffb41379000)
```
It looks like it is possible to compile all of this in statically by changing some Cmake flags. https://stackoverflow.com/questions/24648357/compiling-a-static-executable-with-cmake

**Comment by gajop** [comment]
Willing to try those suggestions yourself? :)

**Comment by Oflameo** [comment]
Yes!

**Comment by Oflameo** [comment]
This is the closest I got to getting something working today.

[output.txt](https://github.com/spring/SpringMapConvNG/files/3478108/output.txt)

**Comment by Oflameo** [comment]
This is the closest I got today.
[output.txt](https://github.com/spring/SpringMapConvNG/files/3478114/output.txt)

**Comment by ashdnazg** [comment]
> add SpringMapConvNG to the spring repo as submodule and let it ship with spring?

Please just do this instead of wasting your time.
Shouldn't take much to add it to the tools folder.

**Comment by Oflameo** [comment]
@ashdnazg You pretty much want me to add SpringMapConvNG to [Rabid](https://springrts.com/wiki/Rapid) and then anyone could install it with a call to [Pr-downloader](https://springrts.com/wiki/Pr-downloader)?

**Comment by ashdnazg** [comment]
No
Add it to https://github.com/spring/spring/tree/develop/tools as a submodule similar to how pr-downloader is there

**Comment by Oflameo** [comment]
Thank you for the clarification. What happens programs after they become sub modules, do they just ship with the engine or do they get pulled with pr-downloader when they are requested?

**Comment by ashdnazg** [comment]
they can ship with the engine like pr-downloader

**Comment by abma** [comment]
should be fixed now, i've added springmapconvng as submodule and it seems to compile on all platforms.

the update of DevIL to mingwlibs possible breaks stuff: please test it, if it works.
